// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFriendKey(arg1, arg2) {
  return window['go']['main']['App']['AddFriendKey'](arg1, arg2);
}

export function AddGroupKey(arg1, arg2) {
  return window['go']['main']['App']['AddGroupKey'](arg1, arg2);
}

export function GetUser() {
  return window['go']['main']['App']['GetUser']();
}

export function JoinDirect(arg1) {
  return window['go']['main']['App']['JoinDirect'](arg1);
}

export function JoinGroup(arg1) {
  return window['go']['main']['App']['JoinGroup'](arg1);
}

export function OnDecrypted(arg1) {
  return window['go']['main']['App']['OnDecrypted'](arg1);
}

export function OnError(arg1) {
  return window['go']['main']['App']['OnError'](arg1);
}

export function SendDirect(arg1, arg2) {
  return window['go']['main']['App']['SendDirect'](arg1, arg2);
}

export function SendGroup(arg1, arg2) {
  return window['go']['main']['App']['SendGroup'](arg1, arg2);
}

export function SetKeyPair(arg1, arg2) {
  return window['go']['main']['App']['SetKeyPair'](arg1, arg2);
}

export function SetUserInfo(arg1) {
  return window['go']['main']['App']['SetUserInfo'](arg1);
}
