// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {storage} from '../models';
import {time} from '../models';
import {chat} from '../models';
import {context} from '../models';

export function AddFriendKey(arg1:string,arg2:string):Promise<void>;

export function AddFriendNSCKey(arg1:string,arg2:string):Promise<void>;

export function AddGroupKey(arg1:string,arg2:string):Promise<void>;

export function CreateGroup():Promise<main.CreateGroupResult>;

export function GetConversation(arg1:string):Promise<storage.StoredConversation>;

export function GetConversationID(arg1:string):Promise<string>;

export function GetMessages(arg1:string,arg2:number,arg3:time.Time):Promise<Array<storage.StoredMessage>>;

export function GetNetworkStatus():Promise<Record<string, any>>;

export function GetUser():Promise<chat.User>;

export function JoinDirect(arg1:string):Promise<void>;

export function JoinGroup(arg1:string,arg2:string):Promise<void>;

export function LoadNSCKeys(arg1:string):Promise<void>;

export function MarkAsRead(arg1:string,arg2:time.Time):Promise<void>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function SearchMessages(arg1:string,arg2:number):Promise<Array<storage.StoredMessage>>;

export function SendDirect(arg1:string,arg2:string):Promise<void>;

export function SendGroup(arg1:string,arg2:string):Promise<void>;

export function SetUserInfo(arg1:string):Promise<void>;
