// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {chat} from '../models';

export function AddFriendKey(arg1:string,arg2:string):Promise<void>;

export function AddGroupKey(arg1:string,arg2:string):Promise<void>;

export function GetConversationID(arg1:string):Promise<string>;

export function GetNetworkStatus():Promise<Record<string, any>>;

export function GetUser():Promise<chat.User>;

export function JoinDirect(arg1:string):Promise<void>;

export function JoinGroup(arg1:string):Promise<void>;

export function OnDecrypted(arg1:any):Promise<void>;

export function OnError(arg1:any):Promise<void>;

export function SendDirect(arg1:string,arg2:string):Promise<void>;

export function SendGroup(arg1:string,arg2:string):Promise<void>;

export function SetKeyPair(arg1:string,arg2:string):Promise<void>;

export function SetUserInfo(arg1:string):Promise<void>;
