// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {chat} from '../models';

export function AddFriendKey(arg1:string,arg2:string):Promise<void>;

export function AddFriendNSCKey(arg1:string,arg2:string):Promise<void>;

export function AddGroupKey(arg1:string,arg2:string):Promise<void>;

export function GenerateSSLCertificate(arg1:Array<string>,arg2:Array<string>,arg3:number):Promise<Record<string, any>>;

export function GetAllDerivedKeys():Promise<Record<string, any>>;

export function GetConversationID(arg1:string):Promise<string>;

export function GetNetworkStatus():Promise<Record<string, any>>;

export function GetUser():Promise<chat.User>;

export function JoinDirect(arg1:string):Promise<void>;

export function JoinGroup(arg1:string):Promise<void>;

export function LoadNSCKeys(arg1:string):Promise<void>;

export function SendDirect(arg1:string,arg2:string):Promise<void>;

export function SendGroup(arg1:string,arg2:string):Promise<void>;

export function SetUserInfo(arg1:string):Promise<void>;
