// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFriendKey(arg1, arg2) {
  return window['go']['main']['App']['AddFriendKey'](arg1, arg2);
}

export function AddFriendNSCKey(arg1, arg2) {
  return window['go']['main']['App']['AddFriendNSCKey'](arg1, arg2);
}

export function AddGroupKey(arg1, arg2) {
  return window['go']['main']['App']['AddGroupKey'](arg1, arg2);
}

export function CreateGroup() {
  return window['go']['main']['App']['CreateGroup']();
}

export function GetAllConversations() {
  return window['go']['main']['App']['GetAllConversations']();
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function GetConversationID(arg1) {
  return window['go']['main']['App']['GetConversationID'](arg1);
}

export function GetMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetMessages'](arg1, arg2, arg3);
}

export function GetNetworkStatus() {
  return window['go']['main']['App']['GetNetworkStatus']();
}

export function GetStartupStatus() {
  return window['go']['main']['App']['GetStartupStatus']();
}

export function GetUser() {
  return window['go']['main']['App']['GetUser']();
}

export function GetUserNSCPublicKey() {
  return window['go']['main']['App']['GetUserNSCPublicKey']();
}

export function JoinDirect(arg1) {
  return window['go']['main']['App']['JoinDirect'](arg1);
}

export function JoinGroup(arg1, arg2) {
  return window['go']['main']['App']['JoinGroup'](arg1, arg2);
}

export function LoadNSCKeys(arg1) {
  return window['go']['main']['App']['LoadNSCKeys'](arg1);
}

export function MarkAsRead(arg1, arg2) {
  return window['go']['main']['App']['MarkAsRead'](arg1, arg2);
}

export function OnShutdown(arg1) {
  return window['go']['main']['App']['OnShutdown'](arg1);
}

export function SearchMessages(arg1, arg2) {
  return window['go']['main']['App']['SearchMessages'](arg1, arg2);
}

export function SendDirect(arg1, arg2) {
  return window['go']['main']['App']['SendDirect'](arg1, arg2);
}

export function SendGroup(arg1, arg2) {
  return window['go']['main']['App']['SendGroup'](arg1, arg2);
}

export function SetUserInfo(arg1) {
  return window['go']['main']['App']['SetUserInfo'](arg1);
}
